server:
  port: 9000

spring:
  application:
    name: auth-server

  security:
    user:
      name: admin
      password: admin123

    oauth2:
      authorizationserver:
        issuer: http://localhost:9000

        client:
          demo-client:
            require-authorization-consent: true

            registration:
              client-id: demo-client
              client-secret: "{noop}demo-secret"
              client-name: Demo Client (Postman)

              # ? Allow both ways Postman can send client credentials
              client-authentication-methods:
                - client_secret_basic
                - client_secret_post

              # ? Allow both code + client_credentials so you can test both flows
              authorization-grant-types:
                - authorization_code
                - refresh_token
                - client_credentials

              # ?? IMPORTANT: Add Postman's callback URL here
              #   Open Postman -> OAuth 2.0 -> "Callback URL"
              #   Usually: https://oauth.pstmn.io/v1/callback
              redirect-uris:
                - https://oauth.pstmn.io/v1/callback

              scopes:
                - openid
                - profile
                - api.read

            token:
              access-token-time-to-live: 30m
              refresh-token-time-to-live: 8h
